# Generated by Django 6.1.1 on 2026-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('adjective', 'Adjective')], max_length=64)),
            ],
        ),
    ]
